# Generated by Django 5.1.4 on 2024-12-31 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiegoPerezPortfolio', '0002_projectimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImages',
        ),
    ]
