# Generated by Django 5.1.4 on 2024-12-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiegoPerezPortfolio', '0003_delete_projectimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
