# Generated by Django 5.2.4 on 2025-08-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiegoPerezPortfolio', '0006_project_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='projects', to='DiegoPerezPortfolio.skill'),
        ),
    ]
