# Generated by Django 5.2.4 on 2025-08-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiegoPerezPortfolio', '0008_project_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
